### PR TITLE
Create Default

### PR DESCRIPTION
**Pull request by makoflagkk**
Thanks Jose for helping me out on this. You're awesome buddie

### CODE REVIEW

**Comment by makoflagkk** [comment]
Pull Request

**Comment by SchneiderAFX** [comment]
i would like you to first elaborate on what does this do, i can't just merge something without knowing first.

**Comment by makoflagkk** [comment]
> i would like you to first elaborate on what does this do, i can't just merge something without knowing first.

I have a better code than Jose. And I will let you know later.

**Comment by makoflagkk** [comment]
> i would like you to first elaborate on what does this do, i can't just merge something without knowing first.

The code that Jose use kinda fucked up the timing lol.

**Comment by makoflagkk** [comment]
Let's have a meeting on Discord tomorrow?

Kyle Kaba

**Comment by makoflagkk** [comment]
This merge will create a flag when your health depleted. It is the same
behavior shown in DDR A3 and GRAND PRIX.

**Comment by makoflagkk** [comment]
It's a health recover flag. But the issue is with Lua what you need to fix
is the end of screentime. When health is set to default to end it doesn't
go show that behavior. I could fix it for you but I am kinda busy with
College.

**Pull request closed without merging**
